### ISSUE TITLE
error in angular v14 and handsontable 12.1

### ISSUE THREAD

**Issue by ericchenty** [TheGr8Nik/Handsontable-key-value-select#14]
zone.js:1711 Uncaught TypeError: Cannot destructure property 'wtOverlays' of 'this.hot.view.wt' as it is undefined.
    at KeyValueSelectEditor.getEditedCell (KeyValueSelect.ts:236:13)
    at KeyValueSelectEditor.refreshDimensions (KeyValueSelect.ts:159:20)
    at KeyValueSelectEditor.open (KeyValueSelect.ts:70:10)
    at KeyValueSelectEditor.beginEditing (baseEditor.mjs:380:12)
    at EditorManager.openEditor (editorManager.mjs:337:25)
    at EditorManager.onCellDblClick (editorManager.mjs:492:14)
    at editorManager.mjs:129:20
    at Event.callListener (event.mjs:410:9)
    at Event.onMouseUp (event.mjs:327:16)
    at HTMLDivElement.<anonymous> (event.mjs:126:24)

**Comment by ericchenty** [comment]
ok, this.hot.view.wt change this.hot.view._wt

**Comment by qingyanmaodai** [comment]
Why can it be changed like this, thank you
